//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiSporKayitSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antrenorler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Antrenorler()
        {
            this.KurKayit = new HashSet<KurKayit>();
        }
    
        public int AntrenorID { get; set; }
        public int BransID { get; set; }
        public string AntrenorTC { get; set; }
        public string AntrenorAdi { get; set; }
        public string AntrenorSoyadi { get; set; }
        public string AntrenorTel { get; set; }
    
        public virtual SporDali SporDali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KurKayit> KurKayit { get; set; }
    }
}
