//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiSporKayitSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int KayitID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> SporID { get; set; }
        public Nullable<int> KursID { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual KurKayit KurKayit { get; set; }
        public virtual SporDali SporDali { get; set; }
    }
}
