//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiSporKayitSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurKayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KurKayit()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public int KurID { get; set; }
        public string KurAdi { get; set; }
        public Nullable<int> DonemID { get; set; }
        public Nullable<System.TimeSpan> SaatBaslangic { get; set; }
        public Nullable<int> Kontenjan { get; set; }
        public Nullable<int> AntrenorID { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTatihi { get; set; }
        public Nullable<System.TimeSpan> SaatBitis { get; set; }
        public Nullable<int> SporDaliID { get; set; }
    
        public virtual Antrenorler Antrenorler { get; set; }
        public virtual Donem Donem { get; set; }
        public virtual SporDali SporDali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
