//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DsiSporKayitSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public int OgrenciID { get; set; }
        public string TCNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> Kilo { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string DogumYeri { get; set; }
        public string KanGrubu { get; set; }
        public string TelNo { get; set; }
        public string Adres { get; set; }
        public string SaglikSorunu { get; set; }
        public string KullanilanIlaclar { get; set; }
        public string Alerjiler { get; set; }
        public string SporGecmisi { get; set; }
        public string YakiniAd { get; set; }
        public string YakiniSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
